name: Docker Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine3.15
    steps:
      - name:  Log Node Version
        run: |
          node -v
          cat /etc/os-release
          pwd
          whoami