name: Matrix

on: pull_request

jobs:
  node-version:
  # Strategy allows to run codes repeatedly with different parameters
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [6, 8, 10]
        include:
          - os: ubuntu-latest
            node-version: 8
            is_ubuntu_8: "true"
        exclude: #Allows us to format our matrix build, to exclude step/steps from our build/workflow
          - os: ubuntu-latest
            node-version: 6
          - os: macos-latest
            node-version: 8
      # max-parallel: 2
  # if fail-fast is true - All jobs will only run if the above is successful
      fail-fast: true
    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_8: ${{ matrix.is_ubunti_8 }}
    steps:
      - name: Log node version
        run: |
          node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Log node version
        run: |
          node -v
          echo $IS_UBUNTU_8