name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World, Welcome to my first GitHub Actions Workflow"
      - name: multiline script
        run: |
          node -v
          npm -v
          v
          mvn -v
